---
label: Product Template
hide_body: true
fields:
- type: datetime
  name: date
  label: date
- type: textarea
  name: description
  label: description
- type: text
  name: id
  label: id
- type: file
  name: image
  label: image
- type: text
  name: name
  label: name
- type: number
  name: price
  label: price
- type: text
  name: product_url
  label: product_url
- name: related_products
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: products
      file: 
      path: 
  label: Related Products
pages:
- content/products/testje.md
